version: '3.4'

services:
  pdfservice:
    image: pdfservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development,
      IS_CLOSE_BROWSER: true,
      IS_WAIT_UNTIL: 'networkidle0'
    ports:
      - 3000:3000
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
