version: '3.4'

services:
  pdfservice:
    image: pdfservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      IS_CLOSE_BROWSER: false
      IS_WAIT_UNTIL: networkidle0
    ports:
      - 3000:3000
    restart: always

